# Generated by Django 5.2.1 on 2025-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('password_check', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('nickname', models.CharField(max_length=100)),
                ('mbti', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('major', models.CharField(max_length=50)),
                ('self_introduce', models.TextField()),
            ],
        ),
    ]
