# Generated by Django 5.2.1 on 2025-06-04 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='default_profile.png', upload_to='')),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('mbti', models.CharField(choices=[('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('비공개', '비공개')], default='비공개', max_length=6)),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성'), ('비공개', '비공개')], default='비공개', max_length=10)),
                ('grade', models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년'), ('4학년', '4학년'), ('비공개', '비공개')], default='비공개', max_length=10)),
                ('college', models.CharField(choices=[('간호대학', '간호대학'), ('경영대학', '경영대학'), ('공과대학', '공과대학'), ('농업생명환경대학', '농업생명환경대학'), ('사회과학대학', '사회과학대학'), ('사범대학', '사범대학'), ('생활과학대학', '생활과학대학'), ('수의과대학', '수의과대학'), ('약학대학', '약학대학'), ('예술학과군', '예술학과군'), ('의과대학', '의과대학'), ('인문대학', '인문대학'), ('자연과학대학', '자연과학대학'), ('전자정보대학', '전자정보대학'), ('창의융합대학', '창의융합대학'), ('충북PRIDE공유대학', '충북PRIDE공유대학'), ('비공개', '비공개')], default='비공개', max_length=50)),
                ('self_introduce', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
