# Generated by Django 5.2.1 on 2025-05-27 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(choices=[('인문대학', '인문대학'), ('사회과학대학', '사회과학대학'), ('자연과학대학', '자연과학대학'), ('경영대학', '경영대학'), ('공과대학', '공과대학'), ('전자정보대학', '전자정보대학'), ('농업생명환경대학', '농업생명환경대학'), ('사범대학', '사범대학'), ('생활과학대학', '생활과학대학'), ('수의과대학', '수의과대학'), ('약학대학', '약학대학'), ('의과대학', '의과대학'), ('간호대학', '간호대학'), ('창의융합대학', '창의융합대학'), ('충북PRIDE공유대학', '충북PRIDE공유대학'), ('예술학과군', '예술학과군'), ('공개 안 함', '공개 안 함')], default='공개 안 함', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성'), ('공개 안 함', '공개 안 함')], default='공개 안 함', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년'), ('4학년', '4학년'), ('공개 안 함', '공개 안 함')], default='공개 안 함', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('공개 안 함', '공개 안 함')], default='공개 안 함', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='user_img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_introduce',
            field=models.TextField(blank=True, default='안녕하세요!', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
