# Generated by Django 5.2.1 on 2025-05-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_college_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='self_introduce',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
