# Generated by Django 5.2.1 on 2025-05-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
