# Generated by Django 5.2.1 on 2025-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, choices=[('인문대학', '인문대학'), ('사회과학대학', '사회과학대학'), ('자연과학대학', '자연과학대학'), ('경영대학', '경영대학'), ('공과대학', '공과대학'), ('전자정보대학', '전자정보대학'), ('농업생명환경대학', '농업생명환경대학'), ('사범대학', '사범대학'), ('생활과학대학', '생활과학대학'), ('수의과대학', '수의과대학'), ('약학대학', '약학대학'), ('의과대학', '의과대학'), ('간호대학', '간호대학'), ('창의융합대학', '창의융합대학'), ('충북PRIDE공유대학', '충북PRIDE공유대학'), ('예술학과군', '예술학과군')], max_length=50, null=True),
        ),
    ]
