# Generated by Django 5.2.1 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_major_profile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='self_introduce',
            field=models.CharField(max_length=50),
        ),
    ]
