# Generated by Django 5.2.1 on 2025-05-14 11:24
# (원하는 경우, 날짜와 버전은 적절히 수정 가능)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
    ]
