# Generated by Django 5.2.1 on 2025-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STUDY', 'STUDY'), ('GAME', 'GAME'), ('EXERCISE', 'EXERCISE'), ('MEALS', 'MEALS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('max_member', models.PositiveIntegerField()),
                ('meet_introduce', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
