# Generated by Django 5.2.1 on 2025-06-04 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STUDY', 'STUDY'), ('GAME', 'GAME'), ('EXERCISE', 'EXERCISE'), ('MEALS', 'MEALS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('max_member', models.CharField(choices=[('1명', '1명'), ('2명', '2명'), ('3명', '3명'), ('4명', '4명'), ('5명', '5명'), ('6명', '6명'), ('7명', '7명'), ('8명', '8명')], max_length=5)),
                ('meet_introduce', models.TextField(blank=True, null=True)),
                ('participant', models.ManyToManyField(blank=True, related_name='joined_meets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
