# Generated by Django 5.2.1 on 2025-05-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='master',
        ),
        migrations.AddField(
            model_name='meet',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='max_member',
            field=models.CharField(choices=[('1명', '1명'), ('2명', '2명'), ('3명', '3명'), ('4명', '4명'), ('5명', '5명'), ('6명', '6명'), ('7명', '7명'), ('8명', '8명')], max_length=5),
        ),
    ]
