# Generated by Django 5.2.1 on 2025-05-20 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_remove_meet_master_meet_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='username',
        ),
        migrations.AddField(
            model_name='meet',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='joined_meets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meets', to=settings.AUTH_USER_MODEL),
        ),
    ]
