# Generated by Django 5.1.8 on 2025-05-28 01:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='deadline',
        ),
    ]
