# Generated by Django 5.1.8 on 2025-05-28 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_meet_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='meet_introduce',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='user',
        ),
        migrations.AddField(
            model_name='meet',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
