# Generated by Django 5.1.8 on 2025-05-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_meet_created_at_remove_meet_meet_introduce_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meet',
        ),
    ]
